### ISSUE TITLE
Provisioning failure

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-traefik-mesh#72] opened 2021-03-10 17:10 UTC
**Description**
```
Details
error applying helm chart: Error applying helm chart: Error applying helm chart: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "prometheus" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "traefik-mesh"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"
```

**Environment:**
- Meshery Version: 
```
➜  ~ mesheryctl version
Client Version: 0.5.0-rc3 	  GitSHA: e6d67a91d0004a3a6a8ba92a8aeb83d9018c4f2a
Server Version: edge-latest 	  GitSHA: d624ec5
Checking for latest version of Meshery...

  0.5.0-rc3 is the latest Meshery release.
```

**Comment by utkarsh-pro** [comment] 2021-03-11 13:05
@leecalcote safe to close this issue as the cause was istio's prometheus and traefik mesh's prometheus conflicting cluster roles? Or should we add that somewhere in the documentation before closing this issue?

**Comment by leecalcote** [comment] 2021-03-11 13:17
A good way to close out this issue is by documenting the probable cause and suggested remediation with an error code dedicated to this failure. @mgfeller, are we ready to start assigning or generating component-specific error codes? // @kumarabd

**Closed** 2021-08-05 21:22 UTC
Labels: kind/bug, area/lifecycle, service-mesh/traefik-mesh
